CREATE USER Mits IDENTIFIED BY MitaliShiba1234;
CREATE USER KK IDENTIFIED BY KaranNupoor1234;
CREATE USER SR IDENTIFIED BY ShibaMitali1234;
CREATE USER Nups IDENTIFIED BY NupoorKaran1234;

GRANT CONNECT,RESOURCE TO Mits;
GRANT CONNECT,RESOURCE TO KK;
GRANT CONNECT,RESOURCE TO SR;
GRANT CONNECT,RESOURCE TO Nups;

GRANT
  SELECT,
  INSERT,
  UPDATE,
  DELETE
ON
  admin.bloodbankstaff
TO
  Mits;
  
GRANT
  SELECT,
  INSERT,
  UPDATE,
  DELETE
ON
  admin.bloodsample
TO
  KK;
  
GRANT
  SELECT,
  INSERT,
  UPDATE,
  DELETE
ON
  admin.DiseaseFinder
TO
  SR;
  
GRANT
  SELECT,
  INSERT,
  UPDATE,
  DELETE
ON
  admin.hospitalinfo
TO
  Nups;

GRANT UNLIMITED TABLESPACE TO Mits;
GRANT UNLIMITED TABLESPACE TO KK;
GRANT UNLIMITED TABLESPACE TO SR;
GRANT UNLIMITED TABLESPACE TO Nups;

CREATE role Staff identified by Staff123;
CREATE role Doctor1 identified by Doctor123;
CREATE role Donor identified by DONOR345;



